export enum TextType {
  HEADING = 'HEADING',
  SUB_HEADING = 'SUB_HEADING',
  BODY = 'BODY',
  LABEL = 'LABEL',
  MD = 'MD',
  SM = 'SM',
  PARAGRAPH = 'PARAGRAPH',
  BUTTON = 'BUTTON',
  BUTTON_SMALL = 'BUTTON_SMALL',
  INPUT = 'INPUT',
}
